### ISSUE TITLE
Remove webui from docker guide

### ISSUE THREAD

**Issue by Undeadhunter** [ShokoAnime/ShokoDocs#25]
Since it's pulled on docker creation.

**Comment by hidden4003** [comment]
You might want to use different version or a custom build if you're testing a bug fix for example.

**Comment by hidden4003** [comment]
@ElementalCrisis cast your vote, but I think this just need to be closed.

**Comment by ElementalCrisis** [comment]
I don't use the docker version, if it's pulled automatically then there's no point for the guide to tell the user to download it separately. However @undeadhunter can just create a PR with that section in the docs removed.

**Comment by Undeadhunter** [comment]
I would say if someone wants to do beta installs they are knowledgeable enough to add the volume manually. Nothing is stopping users from doing it, but it is not something for the normal user. Which we aim the docs for I would assume.

**Comment by ElementalCrisis** [comment]
Could also add a notice but you're right, docs are mainly for the average user.

**Comment by Cazzar** [comment]
Ultimately, the best idea that I can come up with is, if we give the user's a table of paths that they might want to know, `/usr/src/app/build/webui`, `/usr/src/app/build/plugins`, etc...
This would be something moreso for a power user but it would help for not having to dig around the Dockerfile/container

**Comment by Undeadhunter** [comment]
#30
