### ISSUE TITLE
Dark Theme on mobile missing

### ISSUE THREAD

**Issue by alecmeelan** [ShokoAnime/ShokoDocs#39]
The Dark Theme button on mobile is missing even when going into desktop mode for mobile.

**Comment by ElementalCrisis** [comment]
![image](https://user-images.githubusercontent.com/9443295/61607074-efd26a80-ac01-11e9-8092-ca25cbe5d704.png)

Its there but looks like its hidden. Will be fixed when I tackle #37 and get mobile all nice and looking.
