### ISSUE TITLE
shokoanime.com

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDocs#7]
at bottom:
ShokoMed**t**a - A library plugin for Plex (Home Theatre PC’s)

Nakamori – A plugin for Kodi (Home Theatre PC’s) - also I would prefer to stick to proper naming (same as you did with Plex), 

Nakamori - A Kodi addon
also KODI (and plex probably) ain't htpc ;-) Kodi is `media player software application` or from Kodi FAQ: `open source cross-platform software media player and entertainment hub for digital media for HTPCs`

Menu: Program/Plugins: 
Soko on Plex

**Comment by ElementalCrisis** [comment]
I'll fix those spelling mistakes when I get home but I'm a bit confused on the Nakamori part. What do you mean by proper naming?

**Comment by bigretromike** [comment]
Like 'channel' and 'plugin' is used by Plex, the 'addon' term is used by Kodi (in application and documentation) so I sugest sticking with proper naming . nakamori is kodi addon not plugin

**Comment by ElementalCrisis** [comment]
Ah gotcha, I'll make those changes when as well.

**Comment by ElementalCrisis** [comment]
Fixed.
